apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: apikey-auth
  namespace: gloo-system
spec:
  configs:
  - api_key_auth:
      label_selector:
        portals.devportal.solo.io/gloo-system.petstore.petstore-keyscope: "true"